services:
  swapi:
    build:
      context: .
      dockerfile: ./Dockerfile.swapi
    image: swapi:latest
    container_name: "swapi"
    volumes_from:
      - tmp
    depends_on:
      - mongo
      - redis
    networks:
      - swapi_internal
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_URI=/tmp/redis/redis.sock
      - REDIS_NETWORK=unix
    ports:
      - 127.0.0.1:8080:8080
  mongo:
    image: mongo:7.0.3-jammy
    container_name: "mongodb"
    networks:
      - swapi_internal
  redis:
    build:
      context: .
      dockerfile: ./Dockerfile.redis
    image: redis:7.2.3-alpine3.18-custom
    container_name: "redis"
    volumes_from:
      - tmp
    depends_on:
      - tmp
    networks:
      - swapi_internal
  tmp:
    image: busybox
    command: chmod -R 777 /tmp/redis
    volumes:
      - /tmp/redis/

networks:
  swapi_internal:
    driver: bridge